#!/bin/bash

# faster dnf downloads
echo 'max_parallel_downloads=20' | sudo tee --append /etc/dnf/dnf.conf
echo 'deltarpm=true' | sudo tee --append /etc/dnf/dnf.conf

sudo dnf update
sudo dnf group install "base-x"

# enable repositories
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm

# downloading everything we need 
sudo dnf install git make gcc pam-devel libxcb libxcb-devel libX11-devel libXft-devel fedora-workstation-repositories bspwm sxhkd stow pip xset wget unzip vim picom feh polybar imwheel breeze-cursor-theme rofi mpv thunar firefox patch pavucontrol util-linux-user zsh tar lxappearance

# st download
mkdir $HOME/.compiled-apps && cd $HOME/.compiled-apps
cd $HOME/.compiled-apps
git clone https://git.suckless.org/st && cd st
wget -O st-alpha-0.8.5.diff https://st.suckless.org/patches/alpha/st-alpha-20220206-0.8.5.diff
cp config.def.h config.h
patch -i st-alpha-0.8.5.diff
patch -i $HOME/Fedora-Installer/st-patch.diff
sudo make clean install

# dotfiles download
cd $HOME && git clone https://github.com/HelamanWarrior/dotfiles.git && mv dotfiles .dotfiles && cd .dotfiles
stow */

# ff2mpv setup
cd $HOME/.compiled-apps && git clone https://github.com/woodruffw/ff2mpv && cd ff2mpv
./install.sh firefox

# xinitrc setup
cp /etc/X11/xinit/xinitrc $HOME/.xinitrc
echo -e '#!/usr/bin/sh\nexec bspwm' > $HOME/.xinitrc
sudo chmod u+s /usr/bin/xinit
sudo chmod +x $HOME/.xinitrc

# wallpapers
mkdir $HOME/Pictures
cp -r $HOME/Fedora-Installer/Wallpapers $HOME/Pictures/

# download ubuntu nerd font
cd /usr/share/fonts && sudo mkdir ubuntu-nerd-font && cd ubuntu-nerd-font
sudo wget -O Ubuntu.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/UbuntuMono.zip 
sudo unzip Ubuntu.zip && sudo rm Ubuntu.zip
sudo fc-cache -v

# setup theme
cd $HOME/.compiled-apps
git clone https://github.com/TheGreatMcPain/gruvbox-material-gtk.git && cd gruvbox-material-gtk
sudo mkdir $HOME/.local $HOME/.local/share $HOME/.local/share/themes $HOME/.local/share/icons
sudo cp -r themes/* $HOME/.local/share/themes/
sudo cp -r icons/* $HOME/.local/share/icons/
cd $HOME/.compiled-apps && rm -rf gruvbox-material-gtk

# fix mouse cursor
echo -e '[Icon Theme]\nInherits=breeze_cursors' | sudo tee /usr/share/icons/default/index.theme

# setup home directory
cd $HOME && mkdir Desktop Documents Downloads Music Videos

# setup shell 
echo 'After ZSH is done, run the fedora-finish-shell installer executable to theme the shell'
cd $HOME/Fedora-Installer && sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
