#!/bin/bash

# faster dnf downloads
echo 'max_parallel_downloads=20' | sudo tee --append /etc/dnf/dnf.conf
echo 'deltarpm=true' | sudo tee --append /etc/dnf/dnf.conf

sudo dnf update
sudo dnf group install "base-x"

# enable repositories
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/home:/ungoogled_chromium/Fedora_35/home:ungoogled_chromium.repo

# downloading everything we need 
sudo dnf install git make gcc pam-devel libxcb libxcb-devel libX11-devel libXft-devel fedora-workstation-repositories bspwm sxhkd stow pip xset wget unzip vim picom feh polybar imwheel breeze-cursor-theme rofi mpv thunar ungoogled-chromium patch

# st download
mkdir ~/.compiled-apps && cd ~/.compiled-apps
cd ~/.compiled-apps
git clone https://git.suckless.org/st && cd st
wget -O st-alpha-0.8.5.diff https://st.suckless.org/patches/alpha/st-alpha-20220206-0.8.5.diff
patch -i st-alpha.0.8.5.diff
cp config.def.h config.h
patch -i ~/Fedora-Installer/st-patch.diff
sudo make clean install

# dotfiles download
cd ~ && git clone https://github.com/HelamanWarrior/dotfiles.git && mv dotfiles .dotfiles && cd .dotfiles
stow */

# install play-with-mpv
pip install wheel
pip install git+https://github.com/thann/play-with-mpv --user

# xinitrc setup
cp /etc/X11/xinit/xinitrc ~/.xinitrc
echo -e '#!/usr/bin/sh\nexec bspwm' > ~/.xinitrc
sudo chmod u+s /usr/bin/xinit
sudo chmod +x ~/.xinitrc

# wallpapers
mkdir ~/Pictures && mkdir ~/Pictures/Wallpapers && cd ~/Pictures/Wallpapers
git clone https://github.com/vctrblck/gruvbox-wallpapers.git
mv gruvbox-wallpapers/* $PWD/
rm -rf gruvbox-wallpapers

# download ubuntu nerd font
cd /usr/share/fonts && sudo mkdir ubuntu-nerd-font && cd ubuntu-nerd-font
sudo wget -O Ubuntu.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/UbuntuMono.zip 
sudo unzip Ubuntu.zip && sudo rm Ubuntu.zip
sudo fc-cache -v

# setup theme
cd ~/.compiled-apps
git clone https://github.com/TheGreatMcPain/gruvbox-material-gtk.git && cd gruvbox-material-gtk
sudo mkdir ~/.local/share/themes ~/.local/share/icons
sudo cp -r themes/* ~/.local/share/themes/
sudo cp -r icons/* ~/.local/share/icons/
cd ~/.compiled-apps && rm -rf gruvbox-material-gtk

# setup home directory
cd ~ && mkdir Desktop Documents Downloads Videos
