#!/bin/bash
curl -L https://raw.githubusercontent.com/sbugzu/gruvbox-zsh/master/gruvbox.zsh-theme > ~/.oh-my-zsh/custom/themes/gruvbox.zsh-theme
sed -i '/ZSH_THEME=/c\ZSH_THEME="gruvbox"' ~/.zshrc
sed -i '/^ZSH_THEME=.*/a SOLARIZED_THEME="dark"' ~/.zshrc
